export const oldEmpresasCLientes = [
    // {
    //     "sitioWeb": "https://www.icafluor.com/",
    //     "validoHasta": "2023-03-01",
    //     "ultimaEdicion": "2023-03-27T22:29:48.620Z",
    //     "migratedToStudyPlans": true,
    //     "students": [
    //         {
    //             "phone": null,
    //             "country": "México",
    //             "alerts": [],
    //             "status": null,
    //             "progress": 0,
    //             "deparmentId": "",
    //             "email": "guadalupe.chevez@icafluor.com",
    //             "hiringDate": "",
    //             "studyPlan": [],
    //             "time": 0,
    //             "performance": null,
    //             "profileId": null,
    //             "trophy": false,
    //             "birthdate": 1987,
    //             "uid": "Qvc5e59wW2PXhawX644NgFMlriF3",
    //             "score": 0,
    //             "photoUrl": "",
    //             "included": true,
    //             "job": "",
    //             "experience": "Entre 5 y 10 años",
    //             "completedCourses": 0,
    //             "name": "GUADALUPE CHEVEZ RIVES "
    //         },
    //         {
    //             "deparmentId": "",
    //             "score": 0,
    //             "email": "alberto.espinosa@icafluor.com",
    //             "hiringDate": "",
    //             "completedCourses": 0,
    //             "progress": 0,
    //             "studyPlan": [],
    //             "time": 0,
    //             "experience": "Entre 10 y 20 años",
    //             "trophy": false,
    //             "name": "ALBERTO ESPINOSA VAZQUEZ",
    //             "birthdate": 1982,
    //             "phone": null,
    //             "job": "",
    //             "profileId": null,
    //             "photoUrl": "",
    //             "status": null,
    //             "included": true,
    //             "uid": "AIiSmR2CqbgxWKOCY6Q9TMo2qHm1",
    //             "alerts": [],
    //             "performance": null,
    //             "country": "México"
    //         },
    //         {
    //             "phone": null,
    //             "included": true,
    //             "time": 0,
    //             "name": "Roberto Santos Perez",
    //             "job": "",
    //             "birthdate": 1984,
    //             "hiringDate": "",
    //             "completedCourses": 0,
    //             "photoUrl": "",
    //             "studyPlan": [],
    //             "country": "México",
    //             "trophy": false,
    //             "status": null,
    //             "deparmentId": "",
    //             "score": 0,
    //             "performance": null,
    //             "experience": "Entre 1 y 5 años",
    //             "email": "roberto.santos@icafluor.com",
    //             "progress": 0,
    //             "profileId": null,
    //             "alerts": [],
    //             "uid": "y5pQAAoloocZ5KTYwroSvZIVyBn2"
    //         },
    //         {
    //             "uid": "ye1LstfGV2VQPDRI4BSknUkLQyI3",
    //             "status": null,
    //             "birthdate": null,
    //             "email": "adi.roman@icafluor.com",
    //             "name": "Adi Samantha Román Mendoza",
    //             "studyPlan": [],
    //             "progress": 0,
    //             "alerts": [],
    //             "deparmentId": "",
    //             "country": null,
    //             "score": 0,
    //             "phone": null,
    //             "performance": null,
    //             "job": "Administrador",
    //             "hiringDate": "",
    //             "completedCourses": 0,
    //             "time": 0,
    //             "trophy": false,
    //             "included": true,
    //             "experience": "Entre 1 y 5 años",
    //             "profileId": null,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750"
    //         },
    //         {
    //             "progress": 0,
    //             "status": null,
    //             "uid": "2e2DsmCWMae0BS5jFji3etYreYH2",
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "included": true,
    //             "completedCourses": 0,
    //             "birthdate": null,
    //             "score": 0,
    //             "hiringDate": "",
    //             "trophy": false,
    //             "name": "Jesús María Avalos Moreno",
    //             "alerts": [],
    //             "experience": "Entre 10 y 20 años",
    //             "time": 0,
    //             "profileId": null,
    //             "job": "Superintendente de Construcción",
    //             "country": null,
    //             "studyPlan": [],
    //             "deparmentId": "",
    //             "email": "jesusmaria.avalos@icafluor.com",
    //             "performance": null,
    //             "phone": null
    //         },
    //         {
    //             "phone": null,
    //             "performance": null,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "hiringDate": "",
    //             "deparmentId": "",
    //             "country": null,
    //             "birthdate": null,
    //             "studyPlan": [],
    //             "score": 0,
    //             "progress": 0,
    //             "time": 0,
    //             "completedCourses": 0,
    //             "experience": "Entre 10 y 20 años",
    //             "alerts": [],
    //             "name": "José Antonio Pérez Hernández",
    //             "trophy": false,
    //             "job": "Coordinador de Desarrollo de Negocios",
    //             "uid": "FsuUfxHrKRPTkBvou4IWfsFpo5o1",
    //             "email": "joseantonio.perezhernandez@icafluor.com",
    //             "profileId": null,
    //             "included": true,
    //             "status": null
    //         },
    //         {
    //             "studyPlan": [],
    //             "name": "Danny José Rojas Briceño",
    //             "hiringDate": "",
    //             "birthdate": 1990,
    //             "country": "México",
    //             "email": "danny.rojas@icafluor.com",
    //             "alerts": [],
    //             "time": 0,
    //             "progress": 0,
    //             "completedCourses": 0,
    //             "deparmentId": "",
    //             "performance": null,
    //             "uid": "JKbEfW9EwSNoO64dGateCyE0yGy2",
    //             "experience": "Entre 10 y 20 años",
    //             "profileId": null,
    //             "score": 0,
    //             "phone": null,
    //             "status": null,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "included": true,
    //             "trophy": false,
    //             "job": "Jefe de Área de Mantenimiento"
    //         },
    //         {
    //             "country": null,
    //             "birthdate": null,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "alerts": [],
    //             "studyPlan": [],
    //             "time": 0,
    //             "completedCourses": 0,
    //             "score": 0,
    //             "status": null,
    //             "job": "Gerente de Proyecto",
    //             "included": true,
    //             "experience": "Entre 10 y 20 años",
    //             "trophy": false,
    //             "name": "Eduardo   Luis Hoyos Capitaine",
    //             "performance": null,
    //             "profileId": null,
    //             "phone": null,
    //             "progress": 0,
    //             "email": "eduardo.hoyos@icafluor.com",
    //             "uid": "UCLaLAOGV5T6oCnYIqnJUdzYA8l2",
    //             "deparmentId": "",
    //             "hiringDate": ""
    //         },
    //         {
    //             "profileId": null,
    //             "birthdate": 1991,
    //             "time": 0,
    //             "job": "Jefe de Área de Construcción",
    //             "phone": "+52-2294878711",
    //             "studyPlan": [],
    //             "score": 0,
    //             "progress": 0,
    //             "deparmentId": "",
    //             "included": true,
    //             "country": "México",
    //             "performance": null,
    //             "email": "rigoberto.ortega@icafluor.com",
    //             "trophy": false,
    //             "status": null,
    //             "name": "Rigoberto Ortega Abad",
    //             "alerts": [],
    //             "completedCourses": 0,
    //             "hiringDate": "",
    //             "uid": "F9Z6IqOXtQeAY0Bs7m5UiqA3dZA3",
    //             "experience": "Entre 1 y 5 años",
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750"
    //         },
    //         {
    //             "experience": "Entre 10 y 20 años",
    //             "name": "José Luis Valdivia Gil",
    //             "alerts": [],
    //             "status": null,
    //             "time": 0,
    //             "progress": 0,
    //             "profileId": null,
    //             "trophy": false,
    //             "included": true,
    //             "phone": null,
    //             "deparmentId": "",
    //             "studyPlan": [],
    //             "uid": "RtWfUpYZbUVWJC3vJCPUgZ6OLjr2",
    //             "job": "Superintendente de Control de Proyectos",
    //             "birthdate": null,
    //             "performance": null,
    //             "country": null,
    //             "completedCourses": 0,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "email": "jose.valdivia@icafluor.com",
    //             "hiringDate": "",
    //             "score": 0
    //         },
    //         {
    //             "performance": null,
    //             "studyPlan": [],
    //             "trophy": false,
    //             "score": 0,
    //             "name": "Fabian Servín Córdova",
    //             "uid": "bLMfB2L21ETobOZWM2hkiLovZM42",
    //             "job": "Gerente de Proyecto",
    //             "deparmentId": "",
    //             "alerts": [],
    //             "hiringDate": "",
    //             "phone": null,
    //             "country": null,
    //             "profileId": null,
    //             "time": 0,
    //             "email": "fabian.servin@icafluor.com",
    //             "status": null,
    //             "experience": "Entre 10 y 20 años",
    //             "completedCourses": 0,
    //             "included": true,
    //             "progress": 0,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "birthdate": null
    //         },
    //         {
    //             "included": true,
    //             "profileId": null,
    //             "progress": 0,
    //             "job": "Gerente de Sitio",
    //             "completedCourses": 0,
    //             "studyPlan": [],
    //             "performance": null,
    //             "uid": "037VLbmKrCc4DnT99I6Gx1010se2",
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "birthdate": null,
    //             "hiringDate": "",
    //             "time": 0,
    //             "country": null,
    //             "status": null,
    //             "deparmentId": "",
    //             "alerts": [],
    //             "name": "Héctor Martín Sandoval Vélez",
    //             "email": "hector.sandoval@icafluor.com",
    //             "phone": null,
    //             "trophy": false,
    //             "score": 0,
    //             "experience": "Entre 10 y 20 años"
    //         },
    //         {
    //             "phone": null,
    //             "experience": "Entre 10 y 20 años",
    //             "time": 0,
    //             "score": 0,
    //             "country": null,
    //             "deparmentId": "",
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "included": true,
    //             "performance": null,
    //             "uid": "7rzBGBholVcJrmyYNuzPnZnGH9F3",
    //             "status": null,
    //             "email": "guadalupe.alfaro@icafluor.com",
    //             "progress": 0,
    //             "alerts": [],
    //             "studyPlan": [],
    //             "hiringDate": "",
    //             "trophy": false,
    //             "job": "Ingeniero de Proyecto",
    //             "name": "Guadalupe Alfaro Olguin",
    //             "completedCourses": 0,
    //             "profileId": null,
    //             "birthdate": null
    //         },
    //         {
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "email": "islay.jahuey@icafluor.com",
    //             "progress": 0,
    //             "trophy": false,
    //             "status": null,
    //             "name": "Islay   Ali Jahuey Medina",
    //             "studyPlan": [],
    //             "uid": "ons7hd5QeKVKEs3tvh6WocH3nxk1",
    //             "profileId": null,
    //             "birthdate": null,
    //             "experience": "Entre 10 y 20 años",
    //             "score": 0,
    //             "included": true,
    //             "hiringDate": "",
    //             "job": "Supervisor de Control de Proyectos",
    //             "time": 0,
    //             "performance": null,
    //             "alerts": [],
    //             "phone": null,
    //             "deparmentId": "",
    //             "country": null,
    //             "completedCourses": 0
    //         },
    //         {
    //             "progress": 0,
    //             "completedCourses": 0,
    //             "uid": "eiEXxitxH9RRl7DEzfYVbb7rTJD3",
    //             "hiringDate": "",
    //             "name": "Carlos Lozano",
    //             "performance": null,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "trophy": false,
    //             "country": null,
    //             "job": "",
    //             "score": 0,
    //             "phone": null,
    //             "time": 0,
    //             "studyPlan": [],
    //             "birthdate": null,
    //             "deparmentId": "",
    //             "email": "carlos.lozano@icafluor.com",
    //             "alerts": [],
    //             "status": null,
    //             "profileId": null,
    //             "included": true,
    //             "experience": "Más de 20 años"
    //         },
    //         {
    //             "time": 0,
    //             "job": "",
    //             "birthdate": 1964,
    //             "photoUrl": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "completedCourses": 0,
    //             "performance": null,
    //             "uid": "OlKdYb7SNvcctb7JDnN6l3uvXov2",
    //             "email": "juanvicente.castillo@icafluor.com",
    //             "studyPlan": [],
    //             "experience": "Más de 20 años",
    //             "name": "Juan Vicente Castillo",
    //             "score": 0,
    //             "progress": 0,
    //             "trophy": false,
    //             "included": true,
    //             "profileId": null,
    //             "phone": null,
    //             "hiringDate": "",
    //             "status": null,
    //             "alerts": [],
    //             "country": "México",
    //             "deparmentId": ""
    //         }
    //     ],
    //     "fechaDesactivacion": 1666027001314,
    //     "foto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //     "cantCursos": 0,
    //     "status": "active",
    //     "licences": [],
    //     "admins": [
    //         "adi.roman@icafluor.com",
    //         "joseantonio.perezhernandez@icafluor.com",
    //         "carlos.lozano@icafluor.com"
    //     ],
    //     "fechaCreacion": 1664207720361,
    //     "fechaActivacion": 1677077007111,
    //     "ultimoEditor": "OAt1R89V4fXeKXQJ1qLfwF92Dwn1",
    //     "enlaceLinkedin": "",
    //     "resumen": "ICA Fluor es una empresa dedicada a desarrollar la construcción de proyectos y plantas industriales, para el sector público y privado, en México, Centro América y el Caribe.",
    //     "usuarios": [
    //         {
    //             "uid": "Qvc5e59wW2PXhawX644NgFMlriF3",
    //             "fotoPerfil": "",
    //             "registrado": true,
    //             "departamento": "OYM",
    //             "status": "active",
    //             "correo": "guadalupe.chevez@icafluor.com",
    //             "nombre": "GUADALUPE CHEVEZ RIVES ",
    //             "cargo": ""
    //         },
    //         {
    //             "nombre": "ALBERTO ESPINOSA VAZQUEZ",
    //             "uid": "AIiSmR2CqbgxWKOCY6Q9TMo2qHm1",
    //             "fotoPerfil": "",
    //             "cargo": "",
    //             "correo": "alberto.espinosa@icafluor.com",
    //             "status": "active",
    //             "registrado": true,
    //             "departamento": "OYM"
    //         },
    //         {
    //             "correo": "roberto.santos@icafluor.com",
    //             "fotoPerfil": "",
    //             "uid": "y5pQAAoloocZ5KTYwroSvZIVyBn2",
    //             "cargo": "",
    //             "departamento": "OYM",
    //             "registrado": true,
    //             "status": "terminated",
    //             "nombre": "Roberto Santos Perez"
    //         },
    //         {
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "uid": "ye1LstfGV2VQPDRI4BSknUkLQyI3",
    //             "correo": "adi.roman@icafluor.com",
    //             "registrado": true,
    //             "cargo": "Administrador",
    //             "nombre": "Adi Samantha Román Mendoza",
    //             "status": "active",
    //             "departamento": "Administrador"
    //         },
    //         {
    //             "uid": "2e2DsmCWMae0BS5jFji3etYreYH2",
    //             "status": "active",
    //             "cargo": "Superintendente de Construcción",
    //             "registrado": true,
    //             "correo": "jesusmaria.avalos@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "nombre": "Jesús María Avalos Moreno",
    //             "departamento": "Proyectos"
    //         },
    //         {
    //             "uid": "FsuUfxHrKRPTkBvou4IWfsFpo5o1",
    //             "nombre": "José Antonio Pérez Hernández",
    //             "correo": "joseantonio.perezhernandez@icafluor.com",
    //             "status": "active",
    //             "registrado": true,
    //             "cargo": "Coordinador de Desarrollo de Negocios",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "departamento": "Proyectos"
    //         },
    //         {
    //             "uid": "JKbEfW9EwSNoO64dGateCyE0yGy2",
    //             "correo": "danny.rojas@icafluor.com",
    //             "nombre": "Danny José Rojas Briceño",
    //             "registrado": true,
    //             "departamento": "Mantenimiento",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "cargo": "Jefe de Área de Mantenimiento",
    //             "status": "active"
    //         },
    //         {
    //             "cargo": "Gerente de Proyecto",
    //             "status": "active",
    //             "registrado": true,
    //             "nombre": "Eduardo   Luis Hoyos Capitaine",
    //             "uid": "UCLaLAOGV5T6oCnYIqnJUdzYA8l2",
    //             "departamento": "Proyectos",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "correo": "eduardo.hoyos@icafluor.com"
    //         },
    //         {
    //             "registrado": true,
    //             "nombre": "Rigoberto Ortega Abad",
    //             "status": "active",
    //             "correo": "rigoberto.ortega@icafluor.com",
    //             "cargo": "Jefe de Área de Construcción",
    //             "departamento": "Proyectos",
    //             "uid": "F9Z6IqOXtQeAY0Bs7m5UiqA3dZA3",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750"
    //         },
    //         {
    //             "departamento": "Proyectos",
    //             "cargo": "Superintendente de Control de Proyectos",
    //             "registrado": true,
    //             "nombre": "José Luis Valdivia Gil",
    //             "correo": "jose.valdivia@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "uid": "RtWfUpYZbUVWJC3vJCPUgZ6OLjr2",
    //             "status": "active"
    //         },
    //         {
    //             "registrado": true,
    //             "correo": "fabian.servin@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "uid": "bLMfB2L21ETobOZWM2hkiLovZM42",
    //             "departamento": "Proyectos",
    //             "cargo": "Gerente de Proyecto",
    //             "nombre": "Fabian Servín Córdova",
    //             "status": "active"
    //         },
    //         {
    //             "registrado": true,
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "nombre": "Héctor Martín Sandoval Vélez",
    //             "departamento": "Proyectos",
    //             "cargo": "Gerente de Sitio",
    //             "uid": "037VLbmKrCc4DnT99I6Gx1010se2",
    //             "status": "active",
    //             "correo": "hector.sandoval@icafluor.com"
    //         },
    //         {
    //             "nombre": "Guadalupe Alfaro Olguin",
    //             "correo": "guadalupe.alfaro@icafluor.com",
    //             "status": "active",
    //             "uid": "7rzBGBholVcJrmyYNuzPnZnGH9F3",
    //             "departamento": "Proyectos",
    //             "cargo": "Ingeniero de Proyecto",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "registrado": true
    //         },
    //         {
    //             "uid": "ons7hd5QeKVKEs3tvh6WocH3nxk1",
    //             "cargo": "Supervisor de Control de Proyectos",
    //             "departamento": "Proyectos",
    //             "status": "active",
    //             "registrado": true,
    //             "nombre": "Islay   Ali Jahuey Medina",
    //             "correo": "islay.jahuey@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750"
    //         },
    //         {
    //             "correo": "carlos.lozano@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "uid": "eiEXxitxH9RRl7DEzfYVbb7rTJD3",
    //             "status": "active",
    //             "nombre": "Carlos Lozano",
    //             "departamento": "",
    //             "registrado": true,
    //             "cargo": ""
    //         },
    //         {
    //             "registrado": true,
    //             "correo": "juanvicente.castillo@icafluor.com",
    //             "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1664208485164?alt=media&token=5bbd3c30-d2c3-449d-a7b3-eb8e1aba3750",
    //             "cargo": "",
    //             "departamento": "",
    //             "nombre": "Juan Vicente Castillo",
    //             "uid": "OlKdYb7SNvcctb7JDnN6l3uvXov2",
    //             "status": "active"
    //         }
    //     ],
    //     "cantCupos": 16,
    //     "departments": [],
    //     "studyPlansMigratedForStudents": true,
    //     "nombre": "ICA FLUOR OPERACIONES Y MANTENIMIENTO",
    //     "tipo": "suscripcion-empresa",
    //     "creador": "preregistro",
    //     "descripcion": "",
    //     "id": "1664208106966"
    // }
]