export const oldEmpresasCLientes = [
    {
        "sitioWeb": "",
        "tipo": "suscripcion-empresa",
        "students": [
            {
                "studyPlan": [
                    {
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Costos-de-Mantenimiento%2FcostosMantenimiento.webp?alt=media&token=f1e1e52c-7f4a-4430-b285-c2c6a9fd5e01",
                        "cursoCategoria": "Mantenimiento",
                        "pospuesto": false,
                        "puntaje": 0,
                        "fechaInicio": 1676381556058,
                        "certificado": "Z9CnCVDYjvx0vuS6GEsU",
                        "fechaCompletacion": 1692887873903,
                        "fechaFin": 1677072756058,
                        "cursoTitulo": "Gestión de Costos de Mantenimiento",
                        "cursoId": "Gestión-de-Costos-de-Mantenimiento",
                        "duracion": 372,
                        "progreso": 100
                    },
                    {
                        "pospuesto": false,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FMejores-pr%C3%A1cticas-para-la-venta-del-valor-y-los-beneficios-generados-en-la-gesti%C3%B3n-de-mantenimiento%2FventaManenimiento.webp?alt=media&token=806e6fbc-7f29-4854-9b07-4ec6a2844ba4",
                        "duracion": 308,
                        "puntaje": 0,
                        "fechaFin": 1677677556058,
                        "progreso": 100,
                        "fechaInicio": 1677159156058,
                        "cursoCategoria": "Mantenimiento",
                        "certificado": "6WiNT7R1MSkHxcKcwNT5",
                        "cursoId": "Mejores-prácticas-para-la-venta-del-valor-y-los-beneficios-generados-en-la-gestión-de-mantenimiento",
                        "cursoTitulo": "Venta del Valor Generado en la Gestión de Mantenimiento",
                        "fechaCompletacion": 1692891984705
                    },
                    {
                        "progreso": 100,
                        "certificado": "MPZ1inb5MnbSTKkzpwtd",
                        "fechaFin": 1678195956058,
                        "cursoId": "Gestión-de-la-Calidad",
                        "cursoCategoria": "Proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-la-Calidad%2FGestio%CC%81n-de%20la%20Calidad%20(1).png?alt=media&token=8e9cdb90-fe45-4e0f-a60c-2ffcd0192816",
                        "cursoTitulo": "Gestión de la Calidad",
                        "duracion": 222,
                        "puntaje": 0,
                        "pospuesto": false,
                        "fechaCompletacion": 1692896529817,
                        "fechaInicio": 1677763956058
                    },
                    {
                        "puntaje": 0,
                        "progreso": 90,
                        "cursoCategoria": "Proyectos",
                        "cursoId": "Gestión-de-Interfaces",
                        "pospuesto": false,
                        "fechaInicio": 1678282356058,
                        "fechaCompletacion": null,
                        "certificado": "",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Interfaces%2FGestio%CC%81n-de%20la%20Calidad.png?alt=media&token=2dab5d67-3ca8-46b6-b377-06a3a8bd2b2e",
                        "cursoTitulo": "Gestión de Interfaces",
                        "duracion": 182,
                        "fechaFin": 1678627956058
                    },
                    {
                        "fechaInicio": 1678714356058,
                        "cursoCategoria": "Mantenimiento",
                        "progreso": 0,
                        "certificado": "",
                        "pospuesto": false,
                        "cursoId": "Estrategias-de-Mantenimiento",
                        "cursoTitulo": "Estrategias de Mantenimiento",
                        "fechaFin": 1678973556058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FEstrategias-de-Mantenimiento%2FEstrategiaMant.webp?alt=media&token=e34d37f6-c8c6-4e9e-9e59-4d2e1459330f",
                        "fechaCompletacion": null,
                        "puntaje": 0,
                        "duracion": 147
                    },
                    {
                        "cursoCategoria": "Proyectos",
                        "puntaje": 0,
                        "certificado": "",
                        "fechaInicio": 1679059956058,
                        "fechaFin": 1679578356058,
                        "pospuesto": false,
                        "cursoTitulo": "Gestión del Cronograma",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-del-Cronograma%2FGestio%CC%81n-de%20la%20Calidad.png?alt=media&token=c5b8bc4a-647c-4219-8623-fc1a115fbc88",
                        "cursoId": "Gestión-del-Cronograma",
                        "fechaCompletacion": null,
                        "duracion": 268,
                        "progreso": 0
                    },
                    {
                        "cursoId": "Integración-en-la-dirección-de-proyectos",
                        "fechaFin": 1680010356058,
                        "cursoCategoria": "Proyectos",
                        "duracion": 177,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FIntegraci%C3%B3n-en-la-direcci%C3%B3n-de-proyectos%2FImagen-cursos%20(2).png?alt=media&token=fece8071-9139-4cf6-90ba-d4e500b4fa81",
                        "cursoTitulo": "Integración en la Dirección de Proyectos",
                        "progreso": 100,
                        "fechaCompletacion": 1692889110016,
                        "pospuesto": false,
                        "certificado": "MPLpyRVOtogT9o3KiOlM",
                        "puntaje": 0,
                        "fechaInicio": 1679664756058
                    },
                    {
                        "fechaFin": 1680528756058,
                        "pospuesto": false,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-y-Optimizaci%C3%B3n-de-Inventarios-para-Mantenimiento%2FINV.webp?alt=media&token=d05cfbc9-8482-49e3-aa55-608c6c49f202",
                        "progreso": 0,
                        "certificado": "",
                        "fechaInicio": 1680096756058,
                        "fechaCompletacion": null,
                        "cursoId": "Gestión-y-Optimización-de-Inventarios-para-Mantenimiento",
                        "cursoTitulo": "Gestión y Optimización de Inventarios para Mantenimiento",
                        "cursoCategoria": "Mantenimiento",
                        "puntaje": 0,
                        "duracion": 226
                    },
                    {
                        "cursoId": "Administración-del-mantenimiento",
                        "fechaFin": 1681047156058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAdministraci%C3%B3n-del-mantenimiento%2FadminMantenimiento.webp?alt=media&token=57ee864b-476b-4e7b-86fa-c1954b17f653",
                        "puntaje": 0,
                        "cursoCategoria": "Mantenimiento",
                        "duracion": 212,
                        "cursoTitulo": "Administración del Mantenimiento",
                        "certificado": "",
                        "progreso": 0,
                        "fechaCompletacion": null,
                        "fechaInicio": 1680615156058,
                        "pospuesto": false
                    },
                    {
                        "certificado": "",
                        "pospuesto": false,
                        "cursoCategoria": "Confiabilidad",
                        "fechaCompletacion": null,
                        "duracion": 253,
                        "puntaje": 0,
                        "fechaFin": 1681565556058,
                        "fechaInicio": 1681133556058,
                        "cursoTitulo": "Introducción a la Confiabilidad, Disponibilidad y Mantenibilidad",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FIntroducci%C3%B3n-a-la-Confiabilidad%2C-Disponibilidad-y-Mantenibilidad%2Fintroconfi.webp?alt=media&token=9859a75d-cb31-4d45-a17c-264d1808c177",
                        "cursoId": "Introducción-a-la-Confiabilidad,-Disponibilidad-y-Mantenibilidad",
                        "progreso": 0
                    },
                    {
                        "cursoId": "Gestión-de-los-Riesgos",
                        "fechaFin": 1682343156058,
                        "fechaCompletacion": null,
                        "cursoCategoria": "Proyectos",
                        "progreso": 0,
                        "cursoTitulo": "Gestión de los Riesgos",
                        "duracion": 366,
                        "puntaje": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Riesgos%2FImagen-cursos%20(5).png?alt=media&token=4f973015-448c-4cc5-8971-9f096f9716fe",
                        "fechaInicio": 1681651956058,
                        "pospuesto": false,
                        "certificado": ""
                    },
                    {
                        "certificado": "",
                        "cursoTitulo": "Mantenimiento Productivo Total (TPM)",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FMantenimiento-Productivo-Total-(TPM)%2F7-pilares%20de%20madurez%20del%20Mantenimiento.webp?alt=media&token=43181e8d-611e-45ca-90cb-a61b5aa96d73",
                        "duracion": 298,
                        "cursoId": "Mantenimiento-Productivo-Total-(TPM)",
                        "progreso": 0,
                        "puntaje": 0,
                        "fechaCompletacion": null,
                        "pospuesto": false,
                        "fechaFin": 1682947956058,
                        "cursoCategoria": "Mantenimiento",
                        "fechaInicio": 1682429556058
                    },
                    {
                        "cursoId": "Proceso-de-Gestión-de-Mantenimiento",
                        "cursoTitulo": "Proceso de Gestión de Mantenimiento",
                        "certificado": "",
                        "cursoCategoria": "Mantenimiento",
                        "puntaje": 0,
                        "fechaFin": 1683466356058,
                        "progreso": 0,
                        "pospuesto": false,
                        "fechaCompletacion": null,
                        "duracion": 207,
                        "fechaInicio": 1683034356058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FProceso-de-Gesti%C3%B3n-de-Mantenimiento%2FprocesoGestionMant.webp?alt=media&token=9bcd1c5b-f385-442d-b4e9-6533f8f7d3e1"
                    },
                    {
                        "fechaCompletacion": null,
                        "cursoId": "Gestión-de-los-Costos",
                        "duracion": 322,
                        "fechaInicio": 1683552756058,
                        "puntaje": 0,
                        "pospuesto": false,
                        "progreso": 0,
                        "certificado": "",
                        "cursoTitulo": "Gestión de los Costos",
                        "fechaFin": 1684157556058,
                        "cursoCategoria": "Proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Costos%2FImagen-cursos%20(4).png?alt=media&token=0c30af06-79f1-40d1-892b-de6f709ee475"
                    },
                    {
                        "certificado": "",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Interesados%2FGesti%C3%B3n-de%20la%20Calidad.png?alt=media&token=056a04dc-e46f-418e-97d0-7c46cfa967c8",
                        "pospuesto": false,
                        "progreso": 0,
                        "cursoTitulo": "Gestión de los Interesados",
                        "cursoId": "Gestión-de-los-Interesados",
                        "fechaFin": 1684675956058,
                        "cursoCategoria": "Proyectos",
                        "fechaInicio": 1684243956058,
                        "fechaCompletacion": null,
                        "puntaje": 0,
                        "duracion": 209
                    },
                    {
                        "cursoTitulo": "Gestión normalizada de mantenimiento basado en la condición según ISO 17359",
                        "duracion": 453,
                        "cursoCategoria": "Mantenimiento",
                        "puntaje": 0,
                        "progreso": 0,
                        "cursoId": "Gestión-normalizada-de-mantenimiento-basado-en-la-condición-según-ISO-17359",
                        "pospuesto": false,
                        "certificado": "",
                        "fechaFin": 1685539956058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-normalizada-de-mantenimiento-basado-en-la-condici%C3%B3n-seg%C3%BAn-ISO-17359%2FCBM17359.webp?alt=media&token=80414078-291a-4075-85bc-324142c5b51f",
                        "fechaInicio": 1684762356058,
                        "fechaCompletacion": null
                    },
                    {
                        "progreso": 0,
                        "cursoId": "Gestión-de-Mantenimiento",
                        "cursoTitulo": "Gestión de Mantenimiento",
                        "fechaFin": 1686058356058,
                        "cursoCategoria": "Mantenimiento",
                        "puntaje": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Mantenimiento%2FgestionMantenimiento.webp?alt=media&token=c81340b4-2d33-419f-88ce-b19c17c41552",
                        "certificado": "",
                        "pospuesto": false,
                        "duracion": 225,
                        "fechaInicio": 1685626356058,
                        "fechaCompletacion": null
                    },
                    {
                        "cursoCategoria": "Mantenimiento",
                        "fechaFin": 1686922356058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Mantenimiento-en-SAP%2Fsappm.webp?alt=media&token=f3d8bb01-9b07-428d-b217-23c638f17f63",
                        "cursoId": "Gestión-de-Mantenimiento-en-SAP",
                        "pospuesto": false,
                        "fechaInicio": 1686144756058,
                        "duracion": 421,
                        "progreso": 0,
                        "puntaje": 0,
                        "cursoTitulo": "Gestión de Mantenimiento en SAP",
                        "fechaCompletacion": null,
                        "certificado": ""
                    },
                    {
                        "progreso": 0,
                        "certificado": "",
                        "duracion": 133,
                        "fechaInicio": 1687008756058,
                        "cursoTitulo": "Autoevaluación de Mantenimiento",
                        "fechaFin": 1687267956058,
                        "cursoCategoria": "Mantenimiento",
                        "fechaCompletacion": null,
                        "pospuesto": false,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAutoevaluaci%C3%B3n-de-Mantenimiento%2Fautoevaluacion.webp?alt=media&token=bc21b3ea-589a-47b5-88f2-51041f4c28f9",
                        "cursoId": "Autoevaluación-de-Mantenimiento",
                        "puntaje": 0
                    },
                    {
                        "puntaje": 0,
                        "duracion": 153,
                        "fechaInicio": 1687354356058,
                        "certificado": "",
                        "fechaCompletacion": null,
                        "cursoId": "Gestión-de-las-comunicaciones",
                        "progreso": 0,
                        "cursoCategoria": "Proyectos",
                        "pospuesto": false,
                        "cursoTitulo": "Gestión de las Comunicaciones",
                        "fechaFin": 1687613556058,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-las-comunicaciones%2FImagen-cursos%20(6).png?alt=media&token=b8d24ebe-762d-43fd-b92b-62914a7f83f7"
                    },
                    {
                        "cursoTitulo": "Gestión de Paradas de Mantenimiento",
                        "fechaCompletacion": null,
                        "certificado": "",
                        "puntaje": 0,
                        "fechaInicio": 1687699956058,
                        "progreso": 0,
                        "fechaFin": 1688304756058,
                        "pospuesto": false,
                        "cursoCategoria": "Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Paradas-de-Mantenimiento%2Fparada.webp?alt=media&token=fe730389-f1ff-462d-88e8-5356c88806a9",
                        "duracion": 328,
                        "cursoId": "Gestión-de-Paradas-de-Mantenimiento"
                    },
                    {
                        "fechaInicio": 1688391156058,
                        "duracion": 180,
                        "cursoId": "Estándares-de-Planeamiento-y-Control-de-Mantenimiento",
                        "cursoCategoria": "Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FEst%C3%A1ndares-de-Planeamiento-y-Control-de-Mantenimiento%2Fradr.webp?alt=media&token=9e10610d-77b3-440f-9a1a-9e04c3805b0e",
                        "fechaCompletacion": 1682401144575,
                        "certificado": "PL689lpVtU61qZqfNC4Y",
                        "puntaje": 0,
                        "progreso": 100,
                        "fechaFin": 1688736756058,
                        "pospuesto": false,
                        "cursoTitulo": "Estándares de Planeamiento y Control de Mantenimiento"
                    },
                    {
                        "certificado": "",
                        "puntaje": 0,
                        "fechaFin": 1689255156058,
                        "progreso": 0,
                        "cursoCategoria": "Proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAlcance%2FImagen-cursos%20(3).png?alt=media&token=6c67086f-2023-4442-837b-4de4d57b34c0",
                        "fechaInicio": 1688823156058,
                        "pospuesto": false,
                        "cursoTitulo": "Gestión del Alcance",
                        "duracion": 229,
                        "fechaCompletacion": null,
                        "cursoId": "Alcance"
                    },
                    {
                        "progreso": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FPlanificaci%C3%B3n%2C-Programaci%C3%B3n-y-Costos-de-Mantenimiento%2Fpppcm.webp?alt=media&token=db8caa51-37f9-4e3f-8232-369d475f2543",
                        "cursoId": "Planificación,-Programación-y-Costos-de-Mantenimiento",
                        "fechaFin": 1690119156058,
                        "certificado": "",
                        "pospuesto": false,
                        "duracion": 421,
                        "fechaCompletacion": null,
                        "puntaje": 0,
                        "cursoCategoria": "Mantenimiento",
                        "cursoTitulo": "Planificación, Programación y Costos de Mantenimiento",
                        "fechaInicio": 1689341556058
                    },
                    {
                        "cursoCategoria": "Proyectos",
                        "puntaje": 0,
                        "fechaInicio": 1690205556058,
                        "certificado": "",
                        "fechaCompletacion": null,
                        "fechaFin": 1690810356058,
                        "cursoId": "Fundamentos-de-dirección-de-proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FFundamentos-de-direcci%C3%B3n-de-proyectos%2FImagen-cursos.png?alt=media&token=f34c1e13-1d46-40a5-8ae5-649bd09ddfe1",
                        "duracion": 315,
                        "pospuesto": false,
                        "cursoTitulo": "Fundamentos de Dirección de Proyectos",
                        "progreso": 0
                    }
                ],
                "departmentId": "",
                "email": "rtrujillo@osiskodev.com",
                "alerts": [],
                "grade": 0,
                "time": 0,
                "status": null,
                "profileId": null,
                "birthdate": "1990",
                "trophy": false,
                "hiringDate": null,
                "performance": "no plan",
                "hoursPerWeek": 6,
                "phone": "+52-6231069427",
                "progress": 0,
                "experience": "Entre 5 y 10 años",
                "name": "René Trujillo Figueroa",
                "logs": [],
                "score": 0,
                "photoURL": "",
                "country": "México",
                "uid": "JXQpl5gyEuegycq3DXaTnkTxKrL2",
                "included": true,
                "completedCourses": 0
            },
            {
                "name": "Gildardo Vácame Velarde",
                "completedCourses": 0,
                "grade": 0,
                "email": "gildardovacamevelarde@gmail.com",
                "trophy": false,
                "hoursPerWeek": 6,
                "country": "",
                "hiringDate": null,
                "performance": "no plan",
                "profileId": null,
                "uid": "cb7bRfATA3cOBvJ98YGmvnLlqTm1",
                "status": null,
                "time": 0,
                "photoURL": "",
                "progress": 0,
                "birthdate": "",
                "alerts": [],
                "experience": "",
                "logs": [],
                "departmentId": "",
                "score": 0,
                "studyPlan": [
                    {
                        "fechaCompletacion": null,
                        "fechaInicio": 1690551157704,
                        "puntaje": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FLos-lubricantes---Conocimientos-b%C3%A1sicos%2FLos-lubricantes%20-%20los%20conocimientos%20b%C3%A1sicos.webp?alt=media&token=da96277c-2ac5-420b-891c-206b0f31ed19",
                        "cursoCategoria": "Mantenimiento",
                        "duracion": 148,
                        "progreso": 0,
                        "pospuesto": false,
                        "cursoTitulo": "Los lubricantes - Conocimientos básicos",
                        "fechaFin": 1690810357704,
                        "cursoId": "Los-lubricantes---Conocimientos-básicos",
                        "certificado": ""
                    }
                ],
                "included": true
            },
            {
                "grade": 0,
                "trophy": false,
                "status": null,
                "departmentId": "",
                "time": 0,
                "alerts": [],
                "included": true,
                "performance": "no plan",
                "logs": [],
                "progress": 0,
                "hoursPerWeek": 6,
                "photoURL": "",
                "profileId": null,
                "score": 0,
                "completedCourses": 0,
                "country": "",
                "birthdate": "",
                "uid": "ivGmXQBwlHTDzmCDjrqkFMsMekD2",
                "experience": "",
                "email": "elizandroencinasespinoza@gmail.com",
                "name": "Elizandro Encinas Espinoza",
                "studyPlan": [
                    {
                        "cursoCategoria": "Mantenimiento",
                        "duracion": 148,
                        "cursoId": "Los-lubricantes---Conocimientos-básicos",
                        "fechaCompletacion": null,
                        "progreso": 0,
                        "fechaFin": 1690810366403,
                        "fechaInicio": 1690551166403,
                        "puntaje": 0,
                        "certificado": "",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FLos-lubricantes---Conocimientos-b%C3%A1sicos%2FLos-lubricantes%20-%20los%20conocimientos%20b%C3%A1sicos.webp?alt=media&token=da96277c-2ac5-420b-891c-206b0f31ed19",
                        "pospuesto": false,
                        "cursoTitulo": "Los lubricantes - Conocimientos básicos"
                    }
                ],
                "hiringDate": null
            },
            {
                "status": null,
                "studyPlan": [],
                "progress": 0,
                "country": null,
                "score": 0,
                "phone": null,
                "email": "ignaciocoronadoencinas@gmail.com",
                "performance": null,
                "uid": "",
                "time": 0,
                "birthdate": null,
                "experience": null,
                "profileId": null,
                "hiringDate": "",
                "included": true,
                "name": "Ignacio Coronado Encinas",
                "completedCourses": 0,
                "job": "",
                "trophy": false,
                "alerts": [],
                "logs": []
            },
            {
                "score": 0,
                "studyPlan": [],
                "uid": "Viahrq3LpRhJs9vVjB9DBW0CmHE2",
                "logs": [],
                "hiringDate": null,
                "name": "Luis Palma",
                "experience": "Entre 10 y 20 años",
                "grade": 0,
                "birthdate": "",
                "country": "",
                "time": 0,
                "completedCourses": 0,
                "departmentId": "",
                "profileId": null,
                "progress": 0,
                "performance": "no plan",
                "trophy": false,
                "alerts": [],
                "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1677708552244?alt=media&token=e8ddfd20-1638-4a61-8ce0-47b4590f1b66",
                "included": true,
                "status": null,
                "email": "lpalma@osiskodev.com",
                "hoursPerWeek": 6
            },
            {
                "hiringDate": "",
                "logs": [],
                "profileId": null,
                "job": "",
                "studyPlan": [],
                "progress": 0,
                "email": "chureaml@gmail.com",
                "performance": null,
                "trophy": false,
                "time": 0,
                "uid": "",
                "experience": null,
                "alerts": [],
                "country": null,
                "name": "Hébert Arturo Peimbert Araujo",
                "birthdate": null,
                "phone": null,
                "included": true,
                "completedCourses": 0,
                "score": 0,
                "status": null
            },
            {
                "studyPlan": [
                    {
                        "fechaCompletacion": null,
                        "fechaFin": 1676727137269,
                        "cursoId": "Gestión-de-la-Calidad",
                        "fechaInicio": 1676295137269,
                        "cursoCategoria": "Proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-la-Calidad%2FGestio%CC%81n-de%20la%20Calidad%20(1).png?alt=media&token=8e9cdb90-fe45-4e0f-a60c-2ffcd0192816",
                        "progreso": 0,
                        "certificado": "",
                        "pospuesto": false,
                        "puntaje": 0,
                        "duracion": 222,
                        "cursoTitulo": "Gestión de la Calidad"
                    },
                    {
                        "fechaCompletacion": null,
                        "cursoId": "Planificación,-Programación-y-Costos-de-Mantenimiento",
                        "cursoTitulo": "Planificación, Programación y Costos de Mantenimiento",
                        "duracion": 421,
                        "fechaInicio": 1676813537269,
                        "certificado": "",
                        "progreso": 0,
                        "fechaFin": 1677591137269,
                        "pospuesto": false,
                        "puntaje": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FPlanificaci%C3%B3n%2C-Programaci%C3%B3n-y-Costos-de-Mantenimiento%2Fpppcm.webp?alt=media&token=db8caa51-37f9-4e3f-8232-369d475f2543",
                        "cursoCategoria": "Mantenimiento"
                    },
                    {
                        "cursoId": "Gestión-de-los-Interesados",
                        "puntaje": 0,
                        "cursoCategoria": "Proyectos",
                        "cursoTitulo": "Gestión de los Interesados",
                        "certificado": "",
                        "progreso": 0,
                        "duracion": 209,
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Interesados%2FGesti%C3%B3n-de%20la%20Calidad.png?alt=media&token=056a04dc-e46f-418e-97d0-7c46cfa967c8",
                        "fechaFin": 1678109537269,
                        "fechaInicio": 1677677537269,
                        "pospuesto": false
                    },
                    {
                        "fechaInicio": 1678195937269,
                        "puntaje": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Costos-de-Mantenimiento%2FcostosMantenimiento.webp?alt=media&token=f1e1e52c-7f4a-4430-b285-c2c6a9fd5e01",
                        "progreso": 0,
                        "fechaFin": 1678887137269,
                        "pospuesto": false,
                        "cursoTitulo": "Gestión de Costos de Mantenimiento",
                        "cursoId": "Gestión-de-Costos-de-Mantenimiento",
                        "duracion": 372,
                        "fechaCompletacion": null,
                        "cursoCategoria": "Mantenimiento",
                        "certificado": ""
                    },
                    {
                        "fechaInicio": 1678973537269,
                        "cursoTitulo": "Gestión de Mantenimiento",
                        "puntaje": 0,
                        "certificado": "",
                        "cursoCategoria": "Mantenimiento",
                        "fechaFin": 1679405537269,
                        "fechaCompletacion": null,
                        "duracion": 225,
                        "cursoId": "Gestión-de-Mantenimiento",
                        "progreso": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Mantenimiento%2FgestionMantenimiento.webp?alt=media&token=c81340b4-2d33-419f-88ce-b19c17c41552",
                        "pospuesto": false
                    },
                    {
                        "progreso": 0,
                        "cursoCategoria": "Mantenimiento",
                        "cursoId": "Administración-del-mantenimiento",
                        "fechaInicio": 1679491937269,
                        "fechaCompletacion": null,
                        "fechaFin": 1679923937269,
                        "certificado": "",
                        "puntaje": 0,
                        "duracion": 212,
                        "cursoTitulo": "Administración del Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAdministraci%C3%B3n-del-mantenimiento%2FadminMantenimiento.webp?alt=media&token=57ee864b-476b-4e7b-86fa-c1954b17f653",
                        "pospuesto": false
                    },
                    {
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-normalizada-de-mantenimiento-basado-en-la-condici%C3%B3n-seg%C3%BAn-ISO-17359%2FCBM17359.webp?alt=media&token=80414078-291a-4075-85bc-324142c5b51f",
                        "puntaje": 0,
                        "cursoId": "Gestión-normalizada-de-mantenimiento-basado-en-la-condición-según-ISO-17359",
                        "fechaInicio": 1680010337269,
                        "pospuesto": false,
                        "certificado": "",
                        "cursoCategoria": "Mantenimiento",
                        "fechaFin": 1680787937269,
                        "cursoTitulo": "Gestión normalizada de mantenimiento basado en la condición según ISO 17359",
                        "progreso": 0,
                        "duracion": 453
                    },
                    {
                        "certificado": "",
                        "pospuesto": false,
                        "fechaCompletacion": null,
                        "duracion": 315,
                        "cursoId": "Fundamentos-de-dirección-de-proyectos",
                        "cursoTitulo": "Fundamentos de Dirección de Proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FFundamentos-de-direcci%C3%B3n-de-proyectos%2FImagen-cursos.png?alt=media&token=f34c1e13-1d46-40a5-8ae5-649bd09ddfe1",
                        "cursoCategoria": "Proyectos",
                        "fechaInicio": 1680874337269,
                        "fechaFin": 1681479137269,
                        "puntaje": 0,
                        "progreso": 75
                    },
                    {
                        "progreso": 0,
                        "duracion": 180,
                        "cursoTitulo": "Estándares de Planeamiento y Control de Mantenimiento",
                        "cursoCategoria": "Mantenimiento",
                        "certificado": "",
                        "pospuesto": false,
                        "fechaFin": 1681911137269,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FEst%C3%A1ndares-de-Planeamiento-y-Control-de-Mantenimiento%2Fradr.webp?alt=media&token=9e10610d-77b3-440f-9a1a-9e04c3805b0e",
                        "puntaje": 0,
                        "cursoId": "Estándares-de-Planeamiento-y-Control-de-Mantenimiento",
                        "fechaInicio": 1681565537269,
                        "fechaCompletacion": null
                    },
                    {
                        "fechaFin": 1682688737269,
                        "certificado": "",
                        "progreso": 0,
                        "fechaInicio": 1681997537269,
                        "cursoId": "Gestión-de-los-Riesgos",
                        "cursoCategoria": "Proyectos",
                        "puntaje": 0,
                        "duracion": 366,
                        "cursoTitulo": "Gestión de los Riesgos",
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Riesgos%2FImagen-cursos%20(5).png?alt=media&token=4f973015-448c-4cc5-8971-9f096f9716fe",
                        "pospuesto": false
                    },
                    {
                        "puntaje": 0,
                        "pospuesto": false,
                        "duracion": 153,
                        "fechaInicio": 1682775137269,
                        "cursoTitulo": "Gestión de las Comunicaciones",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-las-comunicaciones%2FImagen-cursos%20(6).png?alt=media&token=b8d24ebe-762d-43fd-b92b-62914a7f83f7",
                        "cursoId": "Gestión-de-las-comunicaciones",
                        "cursoCategoria": "Proyectos",
                        "progreso": 0,
                        "fechaCompletacion": null,
                        "certificado": "",
                        "fechaFin": 1683034337269
                    },
                    {
                        "duracion": 308,
                        "fechaCompletacion": null,
                        "pospuesto": false,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FMejores-pr%C3%A1cticas-para-la-venta-del-valor-y-los-beneficios-generados-en-la-gesti%C3%B3n-de-mantenimiento%2FventaManenimiento.webp?alt=media&token=806e6fbc-7f29-4854-9b07-4ec6a2844ba4",
                        "cursoId": "Mejores-prácticas-para-la-venta-del-valor-y-los-beneficios-generados-en-la-gestión-de-mantenimiento",
                        "cursoCategoria": "Mantenimiento",
                        "progreso": 0,
                        "certificado": "",
                        "fechaFin": 1683639137269,
                        "cursoTitulo": "Venta del Valor Generado en la Gestión de Mantenimiento",
                        "puntaje": 0,
                        "fechaInicio": 1683120737269
                    },
                    {
                        "certificado": "",
                        "puntaje": 0,
                        "progreso": 0,
                        "cursoCategoria": "Mantenimiento",
                        "fechaInicio": 1683725537269,
                        "fechaFin": 1684157537269,
                        "pospuesto": false,
                        "cursoId": "Gestión-y-Optimización-de-Inventarios-para-Mantenimiento",
                        "cursoTitulo": "Gestión y Optimización de Inventarios para Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-y-Optimizaci%C3%B3n-de-Inventarios-para-Mantenimiento%2FINV.webp?alt=media&token=d05cfbc9-8482-49e3-aa55-608c6c49f202",
                        "fechaCompletacion": null,
                        "duracion": 226
                    },
                    {
                        "pospuesto": false,
                        "certificado": "",
                        "cursoTitulo": "Estrategias de Mantenimiento",
                        "fechaInicio": 1684243937269,
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FEstrategias-de-Mantenimiento%2FEstrategiaMant.webp?alt=media&token=e34d37f6-c8c6-4e9e-9e59-4d2e1459330f",
                        "progreso": 22.5,
                        "cursoId": "Estrategias-de-Mantenimiento",
                        "puntaje": 0,
                        "fechaFin": 1684503137269,
                        "duracion": 147,
                        "cursoCategoria": "Mantenimiento"
                    },
                    {
                        "cursoCategoria": "Mantenimiento",
                        "pospuesto": false,
                        "duracion": 328,
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Paradas-de-Mantenimiento%2Fparada.webp?alt=media&token=fe730389-f1ff-462d-88e8-5356c88806a9",
                        "fechaInicio": 1684589537269,
                        "puntaje": 0,
                        "progreso": 0,
                        "cursoId": "Gestión-de-Paradas-de-Mantenimiento",
                        "certificado": "",
                        "cursoTitulo": "Gestión de Paradas de Mantenimiento",
                        "fechaFin": 1685194337269
                    },
                    {
                        "fechaInicio": 1685280737269,
                        "progreso": 0,
                        "cursoTitulo": "Proceso de Gestión de Mantenimiento",
                        "puntaje": 0,
                        "certificado": "",
                        "cursoId": "Proceso-de-Gestión-de-Mantenimiento",
                        "pospuesto": false,
                        "fechaFin": 1685712737269,
                        "cursoCategoria": "Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FProceso-de-Gesti%C3%B3n-de-Mantenimiento%2FprocesoGestionMant.webp?alt=media&token=9bcd1c5b-f385-442d-b4e9-6533f8f7d3e1",
                        "duracion": 207,
                        "fechaCompletacion": null
                    },
                    {
                        "pospuesto": false,
                        "cursoId": "Gestión-de-los-Costos",
                        "fechaFin": 1686403937269,
                        "duracion": 322,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-los-Costos%2FImagen-cursos%20(4).png?alt=media&token=0c30af06-79f1-40d1-892b-de6f709ee475",
                        "progreso": 0,
                        "fechaInicio": 1685799137269,
                        "certificado": "",
                        "cursoCategoria": "Proyectos",
                        "cursoTitulo": "Gestión de los Costos",
                        "puntaje": 0,
                        "fechaCompletacion": null
                    },
                    {
                        "progreso": 0,
                        "cursoId": "Mantenimiento-Productivo-Total-(TPM)",
                        "duracion": 298,
                        "puntaje": 0,
                        "fechaFin": 1687008737269,
                        "pospuesto": false,
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FMantenimiento-Productivo-Total-(TPM)%2F7-pilares%20de%20madurez%20del%20Mantenimiento.webp?alt=media&token=43181e8d-611e-45ca-90cb-a61b5aa96d73",
                        "cursoTitulo": "Mantenimiento Productivo Total (TPM)",
                        "cursoCategoria": "Mantenimiento",
                        "fechaInicio": 1686490337269,
                        "certificado": ""
                    },
                    {
                        "puntaje": 0,
                        "fechaCompletacion": null,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-del-Cronograma%2FGestio%CC%81n-de%20la%20Calidad.png?alt=media&token=c5b8bc4a-647c-4219-8623-fc1a115fbc88",
                        "fechaFin": 1687613537269,
                        "duracion": 268,
                        "cursoCategoria": "Proyectos",
                        "certificado": "",
                        "progreso": 0,
                        "pospuesto": false,
                        "cursoId": "Gestión-del-Cronograma",
                        "fechaInicio": 1687095137269,
                        "cursoTitulo": "Gestión del Cronograma"
                    },
                    {
                        "cursoCategoria": "Proyectos",
                        "cursoId": "Alcance",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAlcance%2FImagen-cursos%20(3).png?alt=media&token=6c67086f-2023-4442-837b-4de4d57b34c0",
                        "duracion": 229,
                        "certificado": "",
                        "fechaCompletacion": null,
                        "cursoTitulo": "Gestión del Alcance",
                        "puntaje": 0,
                        "progreso": 0,
                        "pospuesto": false,
                        "fechaInicio": 1687699937269,
                        "fechaFin": 1688131937269
                    },
                    {
                        "cursoCategoria": "Mantenimiento",
                        "fechaCompletacion": null,
                        "cursoTitulo": "Los lubricantes - Conocimientos básicos",
                        "puntaje": 0,
                        "fechaFin": 1688477537269,
                        "duracion": 148,
                        "certificado": "",
                        "cursoId": "Los-lubricantes---Conocimientos-básicos",
                        "progreso": 0,
                        "fechaInicio": 1688218337269,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FLos-lubricantes---Conocimientos-b%C3%A1sicos%2FLos-lubricantes%20-%20los%20conocimientos%20b%C3%A1sicos.webp?alt=media&token=da96277c-2ac5-420b-891c-206b0f31ed19",
                        "pospuesto": false
                    },
                    {
                        "cursoTitulo": "Gestión de Interfaces",
                        "fechaFin": 1688909537269,
                        "puntaje": 0,
                        "fechaInicio": 1688563937269,
                        "cursoId": "Gestión-de-Interfaces",
                        "progreso": 0,
                        "pospuesto": false,
                        "fechaCompletacion": null,
                        "cursoCategoria": "Proyectos",
                        "duracion": 182,
                        "certificado": "",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Interfaces%2FGestio%CC%81n-de%20la%20Calidad.png?alt=media&token=2dab5d67-3ca8-46b6-b377-06a3a8bd2b2e"
                    },
                    {
                        "pospuesto": false,
                        "fechaCompletacion": null,
                        "puntaje": 0,
                        "cursoCategoria": "Equipos Dinámicos",
                        "cursoTitulo": "Bombas Rotativas ",
                        "fechaFin": 1689168737269,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FBombas-Rotativas-%2Frotativas.webp?alt=media&token=0607efed-70c1-4044-9384-05bd3e9f623b",
                        "certificado": "",
                        "duracion": 85,
                        "fechaInicio": 1688995937269,
                        "cursoId": "Bombas-Rotativas-",
                        "progreso": 0
                    },
                    {
                        "fechaInicio": 1689255137269,
                        "fechaFin": 1690032737269,
                        "cursoId": "Gestión-de-Mantenimiento-en-SAP",
                        "cursoCategoria": "Mantenimiento",
                        "fechaCompletacion": null,
                        "puntaje": 0,
                        "progreso": 0,
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FGesti%C3%B3n-de-Mantenimiento-en-SAP%2Fsappm.webp?alt=media&token=f3d8bb01-9b07-428d-b217-23c638f17f63",
                        "cursoTitulo": "Gestión de Mantenimiento en SAP",
                        "duracion": 421,
                        "pospuesto": false,
                        "certificado": ""
                    },
                    {
                        "fechaFin": 1690464737269,
                        "fechaCompletacion": null,
                        "certificado": "",
                        "cursoTitulo": "Integración en la Dirección de Proyectos",
                        "cursoCategoria": "Proyectos",
                        "pospuesto": false,
                        "progreso": 0,
                        "cursoId": "Integración-en-la-dirección-de-proyectos",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FIntegraci%C3%B3n-en-la-direcci%C3%B3n-de-proyectos%2FImagen-cursos%20(2).png?alt=media&token=fece8071-9139-4cf6-90ba-d4e500b4fa81",
                        "duracion": 177,
                        "fechaInicio": 1690119137269,
                        "puntaje": 0
                    },
                    {
                        "cursoCategoria": "Mantenimiento",
                        "certificado": "",
                        "progreso": 0,
                        "cursoTitulo": "Autoevaluación de Mantenimiento",
                        "cursoId": "Autoevaluación-de-Mantenimiento",
                        "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAutoevaluaci%C3%B3n-de-Mantenimiento%2Fautoevaluacion.webp?alt=media&token=bc21b3ea-589a-47b5-88f2-51041f4c28f9",
                        "fechaCompletacion": null,
                        "fechaInicio": 1690551137269,
                        "puntaje": 0,
                        "duracion": 133,
                        "pospuesto": false,
                        "fechaFin": 1690810337269
                    }
                ],
                "included": true,
                "alerts": [],
                "hiringDate": null,
                "name": "Oscar Obregon",
                "country": "",
                "email": "oobregon@osiskodev.com",
                "status": null,
                "experience": "",
                "time": 0,
                "grade": 0,
                "completedCourses": 0,
                "trophy": false,
                "hoursPerWeek": 6,
                "birthdate": "",
                "score": 0,
                "departmentId": "",
                "photoURL": "",
                "uid": "B5z5cRQYexOkiUrPRPrVuG1o2Ow1",
                "progress": 0,
                "performance": "no plan",
                "logs": [],
                "profileId": null
            },
            {
                "studyPlan": [],
                "uid": "R0WCMMs5TbZFARA1BVPe0un28wi2",
                "grade": 0,
                "birthdate": 1697004000000,
                "progress": 0,
                "status": null,
                "logs": [],
                "alerts": [],
                "time": 0,
                "country": "Mexico",
                "trophy": false,
                "profileId": null,
                "departmentId": null,
                "photoURL": "",
                "phone": "+5299992222222",
                "email": "aduarte@osiskodev.com",
                "job": "----",
                "included": true,
                "hoursPerWeek": 6,
                "score": 0,
                "name": "Abel Duarte",
                "experience": "Menos de 1 año",
                "hiringDate": 1697004000000,
                "completedCourses": 0
            },
            {
                "departmentId": null,
                "experience": "11-20 años",
                "birthdate": 259221600000,
                "studyPlan": [],
                "alerts": [],
                "time": 0,
                "trophy": false,
                "phone": "+526231010556",
                "country": "Mexico",
                "status": null,
                "uid": "VvG2cN0bEKYqRyILxrdIpG3ewb82",
                "photoURL": "",
                "hoursPerWeek": 6,
                "included": true,
                "profileId": null,
                "grade": 0,
                "email": "jencinas@osiskodev.com",
                "logs": [],
                "score": 0,
                "job": "Supervisor de mantenimiento ",
                "name": "Jesús Alfredo Encinas Jiménez ",
                "progress": 0,
                "completedCourses": 0,
                "hiringDate": 1317448800000
            },
            {
                "grade": 0,
                "progress": 0,
                "hiringDate": 1479538800000,
                "photoURL": "",
                "job": "Supervisor de Mantenimiento",
                "profileId": "1694629724459",
                "hoursPerWeek": 6,
                "email": "rfelix@osiskodev.com",
                "status": null,
                "studyPlan": [],
                "phone": "+526621458329",
                "birthdate": 558946800000,
                "uid": "YP7nPv26qkS9uWxLqPz6BaySIg43",
                "time": 0,
                "included": true,
                "name": "Raúl Francisco Félix Rubalcava",
                "experience": "11-20 años",
                "trophy": false,
                "completedCourses": 0,
                "score": 0,
                "country": "Mexico",
                "departmentId": "1694629689821",
                "alerts": [],
                "logs": []
            }
        ],
        "foto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1677708552244?alt=media&token=e8ddfd20-1638-4a61-8ce0-47b4590f1b66",
        "ultimaEdicion": "2023-09-06T14:32:13.252Z",
        "creador": "OAt1R89V4fXeKXQJ1qLfwF92Dwn1",
        "studyPlansMigratedForStudents": true,
        "fechaCreacion": 1677708528057,
        "migratedToStudyPlans": true,
        "fechaDesactivacion": null,
        "nombre": "Sapuchi Minera",
        "status": "active",
        "admins": [
            "lpalma@osiskodev.com",
            "admin@osiskodev.com",
            "rtrujillo@osiskodev.com",
            "rfelix@osiskodev.com"
        ],
        "departments": [
            {
                "profiles": [
                    {
                        "responsabilities": [
                            "Asegurar la disponibilidad de los equipos "
                        ],
                        "id": "1694629724459",
                        "name": "Supervisor de mantenimiento.",
                        "skills": [
                            "Planear actividades de mantenimiento"
                        ],
                        "description": "Supervisar y ejecutar las actividades de mantenimiento rutinario. ",
                        "included": true
                    },
                    {
                        "name": "Superintendente de Mantenimiento",
                        "responsabilities": [],
                        "included": true,
                        "description": "Escriba aquí su descripción del perfil",
                        "id": "1694714017382",
                        "skills": []
                    }
                ],
                "users": [
                    {
                        "logs": [],
                        "grade": 0,
                        "score": 0,
                        "uid": "YP7nPv26qkS9uWxLqPz6BaySIg43",
                        "performance": "no plan",
                        "name": "Raúl Francisco Félix Rubalcava",
                        "profileId": "1694629724459",
                        "departmentId": "1694629689821",
                        "job": "Supervisor de Mantenimiento",
                        "included": true,
                        "birthdate": 558946800000,
                        "time": 0,
                        "hiringDate": 1479538800000,
                        "hoursPerWeek": 6,
                        "photoURL": "",
                        "status": "active",
                        "alerts": [],
                        "experience": "11-20 años",
                        "email": "rfelix@osiskodev.com",
                        "trophy": false,
                        "studyPlan": [],
                        "completedCourses": 0,
                        "country": "Mexico",
                        "phone": "+526621458329",
                        "progress": null
                    }
                ],
                "name": "Mantenimiento",
                "id": "1694629689821",
                "color": "FF5263"
            },
            {
                "profiles": [
                    {
                        "description": "Escriba aquí su descripción del perfil",
                        "id": "1694713764798",
                        "name": "Supervisor de Mantenimiento Mina",
                        "included": true,
                        "skills": [],
                        "responsabilities": []
                    }
                ],
                "id": "1694713709279",
                "color": "00BF9C",
                "users": [
                    {
                        "score": 0,
                        "country": "Mexico",
                        "progress": null,
                        "birthdate": 1697004000000,
                        "studyPlan": [],
                        "logs": [],
                        "photoURL": "",
                        "uid": "R0WCMMs5TbZFARA1BVPe0un28wi2",
                        "completedCourses": 0,
                        "alerts": [],
                        "departmentId": "1694713709279",
                        "included": true,
                        "profileId": "1694713764798",
                        "hiringDate": 1697004000000,
                        "phone": "+5299992222222",
                        "performance": "no plan",
                        "experience": "Menos de 1 año",
                        "trophy": true,
                        "status": "active",
                        "grade": 0,
                        "time": 0,
                        "email": "aduarte@osiskodev.com",
                        "name": "Abel Duarte",
                        "hoursPerWeek": 6,
                        "job": "----"
                    }
                ],
                "name": "Mantenimiento Mina"
            }
        ],
        "ultimoEditor": "OAt1R89V4fXeKXQJ1qLfwF92Dwn1",
        "resumen": "",
        "licences": [
            {
                "quantity": 3,
                "couponId": "",
                "id": "1694010706803",
                "createdAt": 1694010706803,
                "retrieveBy": [
                    "aduarte@osiskodev.com",
                    "jencinas@osiskodev.com",
                    "rfelix@osiskodev.com"
                ],
                "status": "active",
                "startedAt": 1678545060000,
                "trialDays": 5,
                "priceId": "Plan-Empresarial-468USD-year",
                "currentPeriodEnd": 1710136800000,
                "currentPeriodStart": 1678545060000
            }
        ],
        "cantCursos": 0,
        "usuarios": [
            {
                "uid": "JXQpl5gyEuegycq3DXaTnkTxKrL2",
                "nombre": "René Trujillo Figueroa",
                "departamento": "",
                "fotoPerfil": "",
                "correo": "rtrujillo@osiskodev.com",
                "cargo": "",
                "status": "active",
                "registrado": true
            },
            {
                "nombre": "Gildardo Vácame Velarde",
                "departamento": "",
                "registrado": true,
                "uid": "cb7bRfATA3cOBvJ98YGmvnLlqTm1",
                "status": "active",
                "fotoPerfil": "",
                "cargo": "",
                "correo": "gildardovacamevelarde@gmail.com"
            },
            {
                "registrado": true,
                "status": "active",
                "cargo": "",
                "departamento": "",
                "uid": "ivGmXQBwlHTDzmCDjrqkFMsMekD2",
                "fotoPerfil": "",
                "nombre": "Elizandro Encinas Espinoza",
                "correo": "elizandroencinasespinoza@gmail.com"
            },
            {
                "uid": "",
                "registrado": false,
                "cargo": "",
                "nombre": "Jesús Alfredo Encinas Jimenez",
                "fotoPerfil": "",
                "correo": "jesusalfredoencinasjimenez@gmail.com",
                "departamento": "",
                "status": "terminated"
            },
            {
                "uid": "",
                "status": "terminated",
                "correo": "ignaciocoronadoencinas@gmail.com",
                "registrado": false,
                "cargo": "",
                "fotoPerfil": "",
                "departamento": "",
                "nombre": "Ignacio Coronado Encinas"
            },
            {
                "nombre": "Luis Palma",
                "registrado": true,
                "fotoPerfil": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1677708552244?alt=media&token=e8ddfd20-1638-4a61-8ce0-47b4590f1b66",
                "uid": "Viahrq3LpRhJs9vVjB9DBW0CmHE2",
                "cargo": "",
                "correo": "lpalma@osiskodev.com",
                "departamento": "",
                "status": "terminated"
            },
            {
                "uid": "",
                "nombre": "Hébert Arturo Peimbert Araujo",
                "cargo": "",
                "registrado": false,
                "correo": "chureaml@gmail.com",
                "departamento": "",
                "status": "terminated",
                "fotoPerfil": ""
            },
            {
                "cargo": "",
                "correo": "oobregon@osiskodev.com",
                "fotoPerfil": "",
                "uid": "B5z5cRQYexOkiUrPRPrVuG1o2Ow1",
                "registrado": true,
                "departamento": "",
                "status": "active",
                "nombre": "Oscar Obregon"
            }
        ],
        "cantCupos": 8,
        "fechaActivacion": 1677770136598,
        "descripcion": "",
        "enlaceLinkedin": "",
        "validoHasta": "2024-03-11",
        "cantUsuarios": 0,
        "id": "sapuchi-minera"
    }
]