// Only users of "aura-minerals" ,"chacoenergias", "colgas", "delsur", "fqml", "gente-oil", "grupo-estrella", "1664208106966", "providencia", "leonali,-s.-de-r.l.-de-c.v", "marelli", "penox-mexico"
export const oldUsers = [
    {
        "uid": "GMlLlmoBcIbqhHoTQwPZ9IncUQn1",
        "email": "admin@delsur.com.sv",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "nombreCompleto": "Administrador delsur",
        "mailchimpTag": "PBUS",
        "especialidad": "Administrador",
        "stripeId": "cus_OabnHIkwumnCnr",
        "fechaRegistro": {
            "seconds": 1694025295,
            "nanoseconds": 422000000
        },
        "displayName": "Administrador delsur",
        "emailVerified": true,
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1682610371335?alt=media&token=05281d6c-c0c3-440e-a00a-8a9c4182860f",
        "titulo": "",
        "paisActual": "",
        "empresaId": "delsur",
        "fechaNacimiento": "",
        "genero": "",
        "index": 16,
        "situacionLaboral": "Administrador",
        "anosExperiencia": "menos de 1 año",
        "empleador": "DELSUR",
        "profesion": "",
        "status": "",
        "tipoUsuario": "suscripcion-empresa",
        "cantCursos": 0,
        "industria": ""
    },
    {
        "uid": "ulu6SVVtZUWO3Ov1uU08wVjYbl33",
        "email": "admin@fqml.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "status": "",
        "empleador": "FQML",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1681752459762?alt=media&token=73af7a02-ad53-4475-a2ca-81cb9cb4cb14",
        "industria": "",
        "titulo": "",
        "tipoUsuario": "suscripcion-empresa",
        "anosExperiencia": "menos de 1 año",
        "index": 16,
        "mailchimpTag": "PBUS",
        "fechaNacimiento": "",
        "situacionLaboral": "Administrador",
        "especialidad": "Administrador",
        "empresaId": "fqml",
        "nombreCompleto": "Administrador",
        "paisActual": "",
        "cantCursos": 0,
        "profesion": "",
        "emailVerified": true,
        "displayName": "Administrador",
        "genero": "",
        "stripeId": "cus_Oac26bq9yJTa5P",
        "fechaRegistro": {
            "seconds": 1694026224,
            "nanoseconds": 620000000
        }
    },
    {
        "uid": "evztQd1bcyc9AAk4WRPwOmMd9Y12",
        "email": "walter.puican@fqml.com",
        "studyPlan": [
            {
                "duracion": 142,
                "fechaInicio": 1690477706770,
                "certificado": "",
                "progreso": 0,
                "fechaFin": 1690736906770,
                "cursoId": "Análisis-de-Criticidad-de-Equipos",
                "cursoCategoria": "Confiabilidad",
                "pospuesto": false,
                "fechaCompletacion": null,
                "cursoFoto": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/Cursos%2FAn%C3%A1lisis-de-Criticidad-de-Equipos%2Fanalisis-de-criticidad.webp?alt=media&token=ec1e36d2-1ff1-49bb-877f-69959ea684b9",
                "puntaje": 0,
                "cursoTitulo": "Análisis de Criticidad de Equipos"
            }
        ],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "tipoUsuario": "suscripcion-empresa",
        "visitasWeb": 7,
        "stripeId": "cus_NmpFveq5WFoJ18",
        "genero": "",
        "paisActual": "",
        "fechaNacimiento": "",
        "cantCursos": 0,
        "fechaRegistro": {
            "seconds": 1682543150,
            "nanoseconds": 1000000
        },
        "emailVerified": true,
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1681752459762?alt=media&token=73af7a02-ad53-4475-a2ca-81cb9cb4cb14",
        "especialidad": "Mantenimiento",
        "empresaId": "fqml",
        "displayName": "Walter Puican Romero",
        "titulo": "",
        "nombreCompleto": "Walter Puican Romero",
        "situacionLaboral": "Superintendente de Control de inventarios",
        "industria": "",
        "mailchimpTag": "PBUS",
        "status": "",
        "ultVisitaWeb": 1689050010583,
        "empleador": "FQML",
        "index": 15,
        "anosExperiencia": "Entre 10 y 20 años",
        "profesion": ""
    },
    {
        "uid": "prduYpCtVkga9HujMw168gRR5eF2",
        "email": "vchiriboga@genteoilecuador.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "tipoUsuario": "suscripcion-empresa",
        "index": 16,
        "titulo": "",
        "stripeId": "cus_OBwUzVLkMENdiQ",
        "displayName": "Veronica Chiriboga",
        "profesion": "",
        "emailVerified": true,
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1685656941132?alt=media&token=a43308dd-931b-434d-a05a-eb12cde14caa",
        "mailchimpTag": "PBUS",
        "genero": "",
        "fechaRegistro": {
            "seconds": 1688336228,
            "nanoseconds": 489000000
        },
        "especialidad": "Recursos Humanos",
        "situacionLaboral": "Coordinadora de Recursos Humanos",
        "empleador": "Gente Oil",
        "anosExperiencia": "Entre 10 y 20 años",
        "status": "",
        "cantCursos": 0,
        "empresaId": "gente-oil",
        "nombreCompleto": "Veronica Chiriboga",
        "fechaNacimiento": "",
        "paisActual": "",
        "industria": ""
    },
    {
        "uid": "vbs9KnWdmdRjakUmKeL1qbgw1ri1",
        "email": "admin@genteoilecuador.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "status": "",
        "anosExperiencia": "menos de 1 año",
        "genero": "",
        "paisActual": "",
        "displayName": "Administrador Gente Oil",
        "profesion": "",
        "especialidad": "Administrador",
        "industria": "",
        "situacionLaboral": "Administrador",
        "titulo": "",
        "stripeId": "cus_OabtLSuzzyGRjE",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1685656941132?alt=media&token=a43308dd-931b-434d-a05a-eb12cde14caa",
        "cantCursos": 0,
        "fechaRegistro": {
            "seconds": 1694025643,
            "nanoseconds": 261000000
        },
        "tipoUsuario": "suscripcion-empresa",
        "fechaNacimiento": "",
        "index": 16,
        "empresaId": "gente-oil",
        "emailVerified": true,
        "mailchimpTag": "PBUS",
        "empleador": "Gente Oil",
        "nombreCompleto": "Administrador Gente Oil"
    },
    {
        "uid": "4nZnBt9RwhUhDzxfUGg5dN2k2Ws1",
        "email": "admin@grupoestrella.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "fechaRegistro": {
            "seconds": 1691677860,
            "nanoseconds": 241000000
        },
        "genero": "",
        "paisActual": "",
        "visitasWeb": 5,
        "stripeId": "cus_OQQlRQ79eXXnbI",
        "especialidad": "Administrador",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1689699550774?alt=media&token=9cc99884-e139-430f-8199-aef221adc1f8",
        "displayName": "Administrador Grupo Estrella",
        "fechaNacimiento": "",
        "profesion": "",
        "nombreCompleto": "Administrador Grupo Estrella",
        "tipoUsuario": "suscripcion-empresa",
        "empresaId": "grupo-estrella",
        "cantCursos": 0,
        "status": "",
        "titulo": "",
        "empleador": "Grupo Estrella",
        "anosExperiencia": "menos de 1 año",
        "index": 16,
        "ultVisitaWeb": 1693239643934,
        "mailchimpTag": "PBUS",
        "emailVerified": true,
        "situacionLaboral": "Administrador",
        "industria": ""
    },
    {
        "uid": "vEcUeenot1SdFU33q7PCSlA0OlF2",
        "email": "admin@providenciaco.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "empresaId": "providencia",
        "index": 16,
        "empleador": "Providencia",
        "situacionLaboral": "Administrador",
        "cantCursos": 0,
        "mailchimpTag": "PBUS",
        "status": "",
        "nombreCompleto": "Administrador Providencia",
        "displayName": "Administrador Providencia",
        "paisActual": "",
        "especialidad": "Administrador",
        "anosExperiencia": "menos de 1 año",
        "stripeId": "cus_OYO6zShvVmkqiG",
        "fechaRegistro": {
            "seconds": 1693513064,
            "nanoseconds": 791000000
        },
        "tipoUsuario": "suscripcion-empresa",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1693512999307?alt=media&token=ee8ccd96-f84a-4973-9eec-da4bac73f24c",
        "profesion": "",
        "titulo": "",
        "industria": "",
        "genero": "",
        "emailVerified": true,
        "fechaNacimiento": ""
    },
    {
        "uid": "CgAiRGQnKPVxMPyMHQwI3rfOkEn1",
        "email": "admin@leonali.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "tipoUsuario": "suscripcion-empresa",
        "index": 16,
        "mailchimpTag": "PBUS",
        "anosExperiencia": "menos de 1 año",
        "emailVerified": true,
        "empleador": "Leonali, S. De R.L. De C.V",
        "situacionLaboral": "Administrador",
        "profesion": "",
        "cantCursos": 0,
        "fechaRegistro": {
            "seconds": 1692802767,
            "nanoseconds": 734000000
        },
        "empresaId": "leonali,-s.-de-r.l.-de-c.v",
        "especialidad": "Administrador",
        "paisActual": "",
        "visitasWeb": 2,
        "ultVisitaWeb": 1695420429643,
        "status": "",
        "displayName": "Administrador Leonali",
        "titulo": "",
        "industria": "",
        "genero": "",
        "nombreCompleto": "Administrador Leonali",
        "fechaNacimiento": "",
        "stripeId": "cus_OVJAXI6ge90C6i",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1692802717026?alt=media&token=9fe04ffd-99c4-44c1-9178-de17216b7506"
    },
    {
        "uid": "ZqOHqNmUlVgGhSk1hNrNQh3efqv2",
        "email": "angel.coyotl@leonali.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "situacionLaboral": "Coordinador de Capacitación",
        "mailchimpTag": "PBUS",
        "titulo": "",
        "nombreCompleto": "Miguel Angel Coyotl",
        "stripeId": "cus_OdfQcsCSxaShQV",
        "displayName": "Miguel Angel Coyotl",
        "cantCursos": 0,
        "genero": "",
        "industria": "",
        "profesion": "",
        "tipoUsuario": "suscripcion-empresa",
        "index": 16,
        "empleador": "Leonali, S. De R.L. De C.V",
        "fechaNacimiento": "",
        "emailVerified": true,
        "anosExperiencia": "Entre 1 y 5 años",
        "paisActual": "",
        "especialidad": "Coordinador de Capacitación",
        "fechaRegistro": {
            "seconds": 1694730644,
            "nanoseconds": 954000000
        },
        "status": "",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1692802717026?alt=media&token=9fe04ffd-99c4-44c1-9178-de17216b7506",
        "empresaId": "leonali,-s.-de-r.l.-de-c.v"
    },
    {
        "uid": "IbGCqqAk5YRQca5LceeByavF81m1",
        "email": "admin@marelli.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "fechaRegistro": {
            "seconds": 1689029604,
            "nanoseconds": 884000000
        },
        "mailchimpTag": "PBUS",
        "situacionLaboral": "Mantenimiento",
        "displayName": "Admin Marelli",
        "fechaNacimiento": "",
        "empresaId": "marelli",
        "cantCursos": 0,
        "stripeId": "cus_OEwrMbnFivjM0l",
        "emailVerified": true,
        "paisActual": "",
        "status": "",
        "genero": "",
        "tipoUsuario": "suscripcion-empresa",
        "nombreCompleto": "Admin Marelli",
        "industria": "",
        "anosExperiencia": "Entre 10 y 20 años",
        "empleador": "Marelli",
        "especialidad": "Mantenimiento",
        "titulo": "",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1689028397889?alt=media&token=fc290d01-9693-4815-b31f-9687700d2f1f",
        "profesion": "",
        "index": 16
    },
    {
        "uid": "dslYRk9qDNe2xYvAGVdMOcOjsR13",
        "email": "admin@penoxmexico.com",
        "studyPlan": [],
        "birthdate": "",
        "hiringDate": "",
        "role": "admin",
        "anosExperiencia": "menos de 1 año",
        "profesion": "",
        "genero": "",
        "displayName": "Administrador",
        "tipoUsuario": "suscripcion-empresa",
        "titulo": "",
        "emailVerified": true,
        "mailchimpTag": "PBUS",
        "photoURL": "https://firebasestorage.googleapis.com/v0/b/predyc-learning.appspot.com/o/EmpresasCliente%2F1681837429148?alt=media&token=ebb3cae9-c5c1-4478-9a8a-34f10760ac86",
        "industria": "",
        "fechaRegistro": {
            "seconds": 1694026431,
            "nanoseconds": 73000000
        },
        "nombreCompleto": "Administrador",
        "paisActual": "",
        "fechaNacimiento": "",
        "empresaId": "penox-mexico",
        "cantCursos": 0,
        "especialidad": "Administrador",
        "empleador": "Penox Mexico",
        "situacionLaboral": "Administrador ",
        "index": 16,
        "stripeId": "cus_Oac67HLX91DolG",
        "status": ""
    }
]