export const particularOldUsers = [
    {
        "id": "00TqdWuqHUOOOaaqP3ScVmvltIN2",
        "emailVerified": true,
        "profesion": "Ingeniero Mecatrónico",
        "fechaUltimaAct": 1668830173117,
        "industria": "Automotriz",
        "ultVisitaWeb": 1687208672284,
        "visitasCarrito": 1,
        "index": 1,
        "telefono": "+52-4771614144",
        "fechaNacimiento": "1986",
        "visitasWeb": 1,
        "situacionLaboral": "Actualmente laborando",
        "nombreCompleto": "Sergio Javier Sanchez Rodríguez",
        "ultVisitaCarrito": 1687208767421,
        "indice": 1,
        "mailchimpTag": "PIND",
        "uid": "00TqdWuqHUOOOaaqP3ScVmvltIN2",
        "photoURL": "https://lh3.googleusercontent.com/a-/ACNPEu-44CoYE5qFw3BKBcLUaWBsG-BN9Or9szTM3BkN0Q=s96-c",
        "puntos": 10,
        "fechaRegistro": {
            "seconds": 1663770877,
            "nanoseconds": 451000000
        },
        "displayName": "Sergio Javier Sanchez Rodríguez",
        "especialidad": "Coordinador de Mantenimiento ",
        "stripeId": "cus_MTQsvhTK9tN6jD",
        "genero": "Masculino",
        "paisActual": "México",
        "anosExperiencia": "Entre 10 y 20 años",
        "canjeados": [
            "perfil-completo-2"
        ],
        "cantCursos": 236,
        "empleador": "Pangea Made",
        "email": "serjav31@gmail.com",
        "titulo": "Título universitario"
    },
    {
        "id": "01c2WETb2kg6iRmqwVy4evYYdvW2",
        "displayName": "Jossmer Marlon Flores Almonacid",
        "fechaNacimiento": "",
        "situacionLaboral": "",
        "titulo": "",
        "anosExperiencia": "",
        "nombreCompleto": "Jossmer Marlon Flores Almonacid",
        "index": 5,
        "stripeId": "cus_MmHEIS4cn15yRT",
        "uid": "01c2WETb2kg6iRmqwVy4evYYdvW2",
        "empleador": "",
        "profesion": "",
        "fechaRegistro": {
            "seconds": 1668117180,
            "nanoseconds": 945000000
        },
        "industria": "",
        "photoURL": "https://lh3.googleusercontent.com/a/ALm5wu0_zEHdbeleDlt8wHsOoqD5o1M71AhLfEsnlslF=s96-c",
        "emailVerified": true,
        "cantCursos": 0,
        "paisActual": "",
        "mailchimpTag": "PIND",
        "especialidad": "",
        "genero": "",
        "email": "floresalmonacid2000@gmail.com"
    },
    {
        "id": "01kLWS3BvQV9MudSxIQ3KZ6omYw2",
        "anosExperiencia": "",
        "empleador": "",
        "industria": "",
        "profesion": "",
        "stripeId": "cus_MlwckXOObTwaao",
        "fechaRegistro": {
            "seconds": 1668040468,
            "nanoseconds": 611000000
        },
        "genero": "",
        "uid": "01kLWS3BvQV9MudSxIQ3KZ6omYw2",
        "index": 5,
        "titulo": "",
        "situacionLaboral": "",
        "telefono": "+52-2224266918",
        "fechaNacimiento": "",
        "photoURL": "https://lh3.googleusercontent.com/a/ALm5wu2zRDVN3YIDsUnnmUb9Zr26tOwCZhvDDY5UVxZuNQ=s96-c",
        "email": "octavio.loredo@grupobersa.com.mx",
        "mailchimpTag": "PIND",
        "displayName": "Octavio Loredo Rocha",
        "emailVerified": true,
        "paisActual": "",
        "cantCursos": 0,
        "especialidad": "",
        "nombreCompleto": "Octavio Loredo Rocha"
    },
    {
        "id": "022AejdWLsVbadSI0D2ccNc7ABm2",
        "nombreCompleto": "Freddy Santos Yugar Méndez",
        "email": "yugarmendez@hotmail.com",
        "genero": "",
        "fechaNacimiento": "",
        "photoURL": "https://lh3.googleusercontent.com/a/ALm5wu2gtxDARHPBFyAgSYyFlnCBCkgJNoVAZI4zYXK2=s96-c",
        "emailVerified": true,
        "profesion": "",
        "especialidad": "",
        "displayName": "Freddy Yugar Méndez",
        "titulo": "",
        "industria": "",
        "stripeId": "cus_Mo5JtvHm4sfRlm",
        "cantCursos": 0,
        "anosExperiencia": "",
        "telefono": "+591-67264822",
        "mailchimpTag": "PIND",
        "fechaRegistro": {
            "seconds": 1668534113,
            "nanoseconds": 328000000
        },
        "empleador": "",
        "paisActual": "",
        "index": 8,
        "uid": "022AejdWLsVbadSI0D2ccNc7ABm2",
        "situacionLaboral": ""
    },
    {
        "id": "02M6qeHjiFhbOy3acHEQeMxzQMA3",
        "uid": "02M6qeHjiFhbOy3acHEQeMxzQMA3",
        "photoURL": "https://lh3.googleusercontent.com/a/ACg8ocLfUeDnRb8UWSVpvWwOpCKEy8oszkdEsS5GIc6xiSDUOI1g=s96-c",
        "visitasWeb": 1,
        "situacionLaboral": "",
        "emailVerified": true,
        "genero": "",
        "nombreCompleto": "Edvin Granillo",
        "anosExperiencia": "",
        "displayName": "Edvin Granillo",
        "titulo": "",
        "cantCursos": 0,
        "empleador": "",
        "paisActual": "",
        "ultVisitaWeb": 1699406736549,
        "fechaNacimiento": "",
        "especialidad": "",
        "profesion": "",
        "email": "edvinalv@gmail.com",
        "mailchimpTag": "PIND",
        "industria": "",
        "fechaRegistro": {
            "seconds": 1699406695,
            "nanoseconds": 936000000
        },
        "index": 17,
        "stripeId": "cus_OxwORjjQz1A3Kk"
    },
    {
        "id": "02YeKoIT5VXXzqzgbrLUg7V7zB32",
        "anosExperiencia": "",
        "fechaRegistro": {
            "seconds": 1668536723,
            "nanoseconds": 893000000
        },
        "photoURL": "https://graph.facebook.com/5572097269539579/picture",
        "especialidad": "",
        "telefono": "+52-4160759417",
        "nombreCompleto": "Mary Angulo",
        "emailVerified": false,
        "situacionLaboral": "",
        "fechaNacimiento": "",
        "industria": "",
        "titulo": "",
        "profesion": "",
        "stripeId": "cus_Mo61psLuPapOGv",
        "empleador": "",
        "uid": "02YeKoIT5VXXzqzgbrLUg7V7zB32",
        "displayName": "Mary Angulo",
        "genero": "",
        "cantCursos": 0,
        "index": 9,
        "mailchimpTag": "PIND",
        "paisActual": "",
        "email": "maryangulo1974@gmail.com"
    },
    {
        "id": "02oGj0rnw0OV5d7bfOzcbW4UBv22",
        "titulo": "",
        "especialidad": "",
        "nombreCompleto": "Claude Hermelin De León.",
        "stripeId": "cus_Mni6FCdYg4Vgxz",
        "empleador": "",
        "fechaNacimiento": "",
        "index": 7,
        "fechaRegistro": {
            "seconds": 1668447779,
            "nanoseconds": 93000000
        },
        "paisActual": "",
        "situacionLaboral": "",
        "profesion": "",
        "uid": "02oGj0rnw0OV5d7bfOzcbW4UBv22",
        "displayName": "Niclauger SA",
        "mailchimpTag": "PIND",
        "telefono": "+502-44990487",
        "photoURL": "https://graph.facebook.com/2026767207513357/picture",
        "industria": "",
        "genero": "",
        "anosExperiencia": "",
        "cantCursos": 0,
        "email": "niclauger1@gmail.com",
        "emailVerified": false
    },
    {
        "id": "02vksfIdliMOeiLAS8OKC3THAvp1",
        "index": 9,
        "genero": "",
        "titulo": "",
        "especialidad": "",
        "email": "luiskhalifa90@gmail.com",
        "profesion": "",
        "displayName": "Luis Angel Mejia Mendez",
        "stripeId": "cus_Mo76pFkjO91fgz",
        "fechaNacimiento": "",
        "cantCursos": 0,
        "paisActual": "",
        "situacionLaboral": "",
        "nombreCompleto": "Luis Angel Mejia Mendez",
        "empleador": "",
        "emailVerified": true,
        "uid": "02vksfIdliMOeiLAS8OKC3THAvp1",
        "photoURL": "https://lh3.googleusercontent.com/a/ALm5wu0udM7xoVCQslIJR7NuDTWhlNoRxS0c4vK3OVPWBw=s96-c",
        "mailchimpTag": "PIND",
        "fechaRegistro": {
            "seconds": 1668540755,
            "nanoseconds": 172000000
        },
        "industria": "",
        "anosExperiencia": ""
    },
    {
        "id": "03Z5jnSNh0Xr6Y0AzekCb33kRKD3",
        "situacionLaboral": "",
        "telefono": "+56-947530749",
        "paisActual": "Chile",
        "photoURL": "https://lh3.googleusercontent.com/a/AGNmyxZCb9jKk_tsCffkYWhbA77EIRbnnwovDlosTXO84g=s96-c",
        "fechaRegistro": {
            "seconds": 1680567283,
            "nanoseconds": 857000000
        },
        "anosExperiencia": "",
        "ultVisitaWeb": 1686271926364,
        "ultVisitaCarrito": 1686271926482,
        "nombreCompleto": "Nelson Castillo",
        "cantCursos": 0,
        "index": 15,
        "fechaUltimaAct": 1681090984644,
        "especialidad": "",
        "titulo": "",
        "formularioCompleto": true,
        "stripeId": "cus_NeG2lpEWkssXon",
        "displayName": "Nelson Castillo",
        "status": "inactive",
        "empleador": "",
        "fechaNacimiento": "25-34",
        "visitasCarrito": 2,
        "mailchimpTag": "PIND",
        "email": "nelson.castillo@alumnos.usm.cl",
        "profesion": "Estudiante",
        "genero": "",
        "uid": "03Z5jnSNh0Xr6Y0AzekCb33kRKD3",
        "visitasWeb": 7,
        "emailVerified": true,
        "industria": ""
    },
    {
        "id": "03fuYATmnQfjweLYWU4tHaXsOEi1",
        "paisActual": "",
        "telefono": "+58-4129370868",
        "mailchimpTag": "PIND",
        "photoURL": "https://lh3.googleusercontent.com/a/ALm5wu297oaD2Ucl-9OtMQH18ZcKcDy6mwfGUwQfCRwP=s96-c",
        "especialidad": "",
        "uid": "03fuYATmnQfjweLYWU4tHaXsOEi1",
        "index": 10,
        "stripeId": "cus_MoWaJ85WJec26O",
        "emailVerified": true,
        "fechaNacimiento": "",
        "email": "cegehdler@gmail.com",
        "titulo": "",
        "anosExperiencia": "",
        "displayName": "Carlos Elias Gehdler",
        "nombreCompleto": "Carlos Elias Gehdler",
        "cantCursos": 0,
        "industria": "",
        "situacionLaboral": "",
        "genero": "",
        "empleador": "",
        "fechaRegistro": {
            "seconds": 1668635590,
            "nanoseconds": 126000000
        },
        "profesion": ""
    }
]